### Dataset Used : Titanic ( https://www.kaggle.com/c/titanic )

This dataset basically includes information regarding all the passengers on Titanic . Various attributes of passengers like age , sex , class ,etc. is recorded and final label 'survived' determines whether or the passenger survived or not .

## Columns  

**Survived:** Outcome of survival (0 = No; 1 = Yes)  
**Pclass:** Socio-economic class (1 = Upper class; 2 = Middle class; 3 = Lower class)  
**Name:** Name of passenger  
**Sex:** Sex of the passenger  
**Age:** Age of the passenger (Some entries contain NaN)  
**SibSp:** Number of siblings and spouses of the passenger aboard  
**Parch:** Number of parents and children of the passenger aboard  
**Ticket:** Ticket number of the passenger  
**Fare:** Fare paid by the passenger  
**Cabin:** Cabin number of the passenger (Some entries contain NaN)  
**Embarked:** Port of embarkation of the passenger (C = Cherbourg; Q = Queenstown; S = Southampton)

In [4]:
import pandas as pd
df = pd.read_csv('titanic-data.csv', index_col=0)

In [5]:
df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
df.columns

Index(['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# Numerical Variables  
1. Age  
2. SibSp  
3. Parch  
4. Fare

In [8]:
df['Age']

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
6       NaN
7      54.0
8       2.0
9      27.0
10     14.0
11      4.0
12     58.0
13     20.0
14     39.0
15     14.0
16     55.0
17      2.0
18      NaN
19     31.0
20      NaN
21     35.0
22     34.0
23     15.0
24     28.0
25      8.0
26     38.0
27      NaN
28     19.0
29      NaN
30      NaN
       ...
862    21.0
863    48.0
864     NaN
865    24.0
866    42.0
867    27.0
868    31.0
869     NaN
870     4.0
871    26.0
872    47.0
873    33.0
874    47.0
875    28.0
876    15.0
877    20.0
878    19.0
879     NaN
880    56.0
881    25.0
882    33.0
883    22.0
884    28.0
885    25.0
886    39.0
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

In [10]:
# It does not make sense to use unique
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [11]:
df['Fare']

PassengerId
1        7.2500
2       71.2833
3        7.9250
4       53.1000
5        8.0500
6        8.4583
7       51.8625
8       21.0750
9       11.1333
10      30.0708
11      16.7000
12      26.5500
13       8.0500
14      31.2750
15       7.8542
16      16.0000
17      29.1250
18      13.0000
19      18.0000
20       7.2250
21      26.0000
22      13.0000
23       8.0292
24      35.5000
25      21.0750
26      31.3875
27       7.2250
28     263.0000
29       7.8792
30       7.8958
         ...
862     11.5000
863     25.9292
864     69.5500
865     13.0000
866     13.0000
867     13.8583
868     50.4958
869      9.5000
870     11.1333
871      7.8958
872     52.5542
873      5.0000
874      9.0000
875     24.0000
876      7.2250
877      9.8458
878      7.8958
879      7.8958
880     83.1583
881     26.0000
882      7.8958
883     10.5167
884     10.5000
885      7.0500
886     29.1250
887     13.0000
888     30.0000
889     23.4500
890     30.0000
891      7.7500
Name: Fare, Length: 891, dtype: float64

### Age and Fare are Continuous Variable

In [12]:
df['SibSp']

PassengerId
1      1
2      1
3      0
4      1
5      0
6      0
7      0
8      3
9      0
10     1
11     1
12     0
13     0
14     1
15     0
16     0
17     4
18     0
19     1
20     0
21     0
22     0
23     0
24     0
25     3
26     1
27     0
28     3
29     0
30     0
      ..
862    1
863    0
864    8
865    0
866    0
867    1
868    0
869    0
870    1
871    0
872    1
873    0
874    0
875    1
876    0
877    0
878    0
879    0
880    0
881    0
882    0
883    0
884    0
885    0
886    0
887    0
888    0
889    1
890    0
891    0
Name: SibSp, Length: 891, dtype: int64

In [14]:
df['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [15]:
df['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

## Parch and SibSp are Discrete Variables

## Categorical Variables  
1. Name  
2. Cabin  
3. Sex  
4. Embarked  
5. Survived  
6. Pclass

## Nominal Values

In [17]:
df['Sex'].unique()

array(['male', 'female'], dtype=object)

In [18]:
# it does not make sense to use unique on Name
df['Name'].unique()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Williams, Mr. Charles Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Masselmani, Mrs. Fatima', 'Fynney, Mr. Joseph J',
       'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"',
       'Sloper, Mr. William Thompson', 'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
       'Emir, Mr. Farred Chehab', 'Fortune, Mr. Charles Alexander',
       'O\'Dwyer, Miss. Ellen "Nellie"', 'Todoroff, Mr. Lalio',
       'Uruchurtu, Don. Manuel E',
       'Spencer, Mrs. William Augustus (Marie Eugenie)',
       'Glynn, Miss. Mary Agatha', 'Wheadon, Mr. Edward H',
       'Meyer, Mr. Edgar Joseph', 'Holverson, Mr. Alexander Oskar',
       'Mamee, Mr. Hanna', 'Cann, Mr. Ernest Charles',
       'Vander Planke, Miss. Augusta Maria',
       'Nicola-Yarred, Miss. Jamila',
       'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
       'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
       'Kraeff, Mr. Theodor', 'Laroche, Miss. Simonne Marie Anne Andree',
       'Devaney, Miss. Margaret Delia', 'Rogers, Mr. William John',
       'Lennon, Mr. Denis', "O'Driscoll, Miss. Bridget",
       'Samaan, Mr. Youssef',
       'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
       'Panula, Master. Juha Niilo', 'Nosworthy, Mr. Richard Cater',
       'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
       'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
       'Ostby, Mr. Engelhart Cornelius', 'Woolner, Mr. Hugh',
       'Rugg, Miss. Emily', 'Novel, Mr. Mansouer',
       'West, Miss. Constance Mirium',
       'Goodwin, Master. William Frederick', 'Sirayanian, Mr. Orsen',
       'Icard, Miss. Amelie', 'Harris, Mr. Henry Birkhardt',
       'Skoog, Master. Harald', 'Stewart, Mr. Albert A',
       'Moubarek, Master. Gerios', 'Nye, Mrs. (Elizabeth Ramell)',
       'Crease, Mr. Ernest James', 'Andersson, Miss. Erna Alexandra',
       'Kink, Mr. Vincenz', 'Jenkin, Mr. Stephen Curnow',
       'Goodwin, Miss. Lillian Amy', 'Hood, Mr. Ambrose Jr',
       'Chronopoulos, Mr. Apostolos', 'Bing, Mr. Lee',
       'Moen, Mr. Sigurd Hansen', 'Staneff, Mr. Ivan',
       'Moutal, Mr. Rahamin Haim', 'Caldwell, Master. Alden Gates',
       'Dowdell, Miss. Elizabeth', 'Waelens, Mr. Achille',
       'Sheerlinck, Mr. Jan Baptist', 'McDermott, Miss. Brigdet Delia',
       'Carrau, Mr. Francisco M', 'Ilett, Miss. Bertha',
       'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
       'Ford, Mr. William Neal', 'Slocovski, Mr. Selman Francis',
       'Fortune, Miss. Mabel Helen', 'Celotti, Mr. Francesco',
       'Christmann, Mr. Emil', 'Andreasson, Mr. Paul Edvin',
       'Chaffee, Mr. Herbert Fuller', 'Dean, Mr. Bertram Frank',
       'Coxon, Mr. Daniel', 'Shorney, Mr. Charles Joseph',
       'Goldschmidt, Mr. George B', 'Greenfield, Mr. William Bertram',
       'Doling, Mrs. John T (Ada Julia Bone)', 'Kantor, Mr. Sinai',
       'Petranec, Miss. Matilda', 'Petroff, Mr. Pastcho ("Pentcho")',
       'White, Mr. Richard Frasar', 'Johansson, Mr. Gustaf Joel',
       'Gustafsson, Mr. Anders Vilhelm', 'Mionoff, Mr. Stoytcho',
       'Salkjelsvik, Miss. Anna Kristine', 'Moss, Mr. Albert Johan',
       'Rekic, Mr. Tido', 'Moran, Miss. Bertha',
       'Porter, Mr. Walter Chamberlain', 'Zabour, Miss. Hileni',
       'Barton, Mr. David John', 'Jussila, Miss. Katriina',
       'Attalah, Miss. Malake', 'Pekoniemi, Mr. Edvard',
       'Connors, Mr. Patrick', 'Turpin, Mr. William John Robert',
       'Baxter, Mr. Quigg Edmond', 'Andersson, Miss. Ellis Anna Maria',
       'Hickman, Mr. Stanley George', 'Moore, Mr. Leonard Charles',
       'Nasser, Mr. Nicholas', 'Webber, Miss. Susan',
       'White, Mr. Percival Wayland', 'Nicola-Yarred, Master. Elias',
       'McMahon, Mr. Martin', 'Madsen, Mr. Fridtjof Arne',
       'Peter, Miss. Anna', 'Ekstrom, Mr. Johan', 'Drazenoic, Mr. Jozef',
       'Coelho, Mr. Domingos Fernandeo',
       'Robins, Mrs. Alexander A (Grace Charity Laury)',
       'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
       'Sobey, Mr. Samuel James Hayden', 'Richard, Mr. Emile',
       'Newsom, Miss. Helen Monypeny', 'Futrelle, Mr. Jacques Heath',
       'Osen, Mr. Olaf Elon', 'Giglio, Mr. Victor',
       'Boulos, Mrs. Joseph (Sultana)', 'Nysten, Miss. Anna Sofia',
       'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
       'Burke, Mr. Jeremiah', 'Andrew, Mr. Edgardo Samuel',
       'Nicholls, Mr. Joseph Charles',
       'Andersson, Mr. August Edvard ("Wennerstrom")',
       'Ford, Miss. Robina Maggie "Ruby"',
       'Navratil, Mr. Michel ("Louis M Hoffman")',
       'Byles, Rev. Thomas Roussel Davids', 'Bateman, Rev. Robert James',
       'Pears, Mrs. Thomas (Edith Wearne)', 'Meo, Mr. Alfonzo',
       'van Billiard, Mr. Austin Blyler', 'Olsen, Mr. Ole Martin',
       'Williams, Mr. Charles Duane', 'Gilnagh, Miss. Katherine "Katie"',
       'Corn, Mr. Harry', 'Smiljanic, Mr. Mile',
       'Sage, Master. Thomas Henry', 'Cribb, Mr. John Hatfield',
       'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
       'Bengtsson, Mr. John Viktor', 'Calic, Mr. Jovo',
       'Panula, Master. Eino Viljami',
       'Goldsmith, Master. Frank John William "Frankie"',
       'Chibnall, Mrs. (Edith Martha Bowerman)',
       'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
       'Baumann, Mr. John D', 'Ling, Mr. Lee',
       'Van der hoef, Mr. Wyckoff', 'Rice, Master. Arthur',
       'Johnson, Miss. Eleanor Ileen', 'Sivola, Mr. Antti Wilhelm',
       'Smith, Mr. James Clinch', 'Klasen, Mr. Klas Albin',
       'Lefebre, Master. Henry Forbes', 'Isham, Miss. Ann Elizabeth',
       'Hale, Mr. Reginald', 'Leonard, Mr. Lionel',
       'Sage, Miss. Constance Gladys', 'Pernot, Mr. Rene',
       'Asplund, Master. Clarence Gustaf Hugo',
       'Becker, Master. Richard F', 'Kink-Heilmann, Miss. Luise Gretchen',
       'Rood, Mr. Hugh Roscoe',
       'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
       'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
       'Bourke, Mr. John', 'Turcin, Mr. Stjepan', 'Pinsky, Mrs. (Rosa)',
       'Carbines, Mr. William',
       'Andersen-Jensen, Miss. Carla Christine Nielsine',
       'Navratil, Master. Michel M',
       'Brown, Mrs. James Joseph (Margaret Tobin)',
       'Lurette, Miss. Elise', 'Mernagh, Mr. Robert',
       'Olsen, Mr. Karl Siegwart Andreas',
       'Madigan, Miss. Margaret "Maggie"',
       'Yrois, Miss. Henriette ("Mrs Harbeck")',
       'Vande Walle, Mr. Nestor Cyriel', 'Sage, Mr. Frederick',
       'Johanson, Mr. Jakob Alfred', 'Youseff, Mr. Gerious',
       'Cohen, Mr. Gurshon "Gus"', 'Strom, Miss. Telma Matilda',
       'Backstrom, Mr. Karl Alfred', 'Albimona, Mr. Nassef Cassem',
       'Carr, Miss. Helen "Ellen"', 'Blank, Mr. Henry', 'Ali, Mr. Ahmed',
       'Cameron, Miss. Clear Annie', 'Perkin, Mr. John Henry',
       'Givard, Mr. Hans Kristensen', 'Kiernan, Mr. Philip',
       'Newell, Miss. Madeleine', 'Honkanen, Miss. Eliina',
       'Jacobsohn, Mr. Sidney Samuel', 'Bazzani, Miss. Albina',
       'Harris, Mr. Walter', 'Sunderland, Mr. Victor Francis',
       'Bracken, Mr. James H', 'Green, Mr. George Henry',
       'Nenkoff, Mr. Christo', 'Hoyt, Mr. Frederick Maxfield',
       'Berglund, Mr. Karl Ivar Sven', 'Mellors, Mr. William John',
       'Lovell, Mr. John Hall ("Henry")', 'Fahlstrom, Mr. Arne Jonas',
       'Lefebre, Miss. Mathilde',
       'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
       'Larsson, Mr. Bengt Edvin', 'Sjostedt, Mr. Ernst Adolf',
       'Asplund, Miss. Lillian Gertrud',
       'Leyson, Mr. Robert William Norman',
       'Harknett, Miss. Alice Phoebe', 'Hold, Mr. Stephen',
       'Collyer, Miss. Marjorie "Lottie"',
       'Pengelly, Mr. Frederick William', 'Hunt, Mr. George Henry',
       'Zabour, Miss. Thamine', 'Murphy, Miss. Katherine "Kate"',
       'Coleridge, Mr. Reginald Charles', 'Maenpaa, Mr. Matti Alexanteri',
       'Attalah, Mr. Sleiman', 'Minahan, Dr. William Edward',
       'Lindahl, Miss. Agda Thorilda Viktoria',
       'Hamalainen, Mrs. William (Anna)', 'Beckwith, Mr. Richard Leonard',
       'Carter, Rev. Ernest Courtenay', 'Reed, Mr. James George',
       'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
       'Stead, Mr. William Thomas', 'Lobb, Mr. William Arthur',
       'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
       'Touma, Mrs. Darwis (Hanne Youssef Razi)',
       'Thorne, Mrs. Gertrude Maybelle', 'Cherry, Miss. Gladys',
       'Ward, Miss. Anna', 'Parrish, Mrs. (Lutie Davis)',
       'Smith, Mr. Thomas', 'Asplund, Master. Edvin Rojj Felix',
       'Taussig, Mr. Emil', 'Harrison, Mr. William', 'Henry, Miss. Delia',
       'Reeves, Mr. David', 'Panula, Mr. Ernesti Arvid',
       'Persson, Mr. Ernst Ulrik',
       'Graham, Mrs. William Thompson (Edith Junkins)',
       'Bissette, Miss. Amelia', 'Cairns, Mr. Alexander',
       'Tornquist, Mr. William Henry',
       'Mellinger, Mrs. (Elizabeth Anne Maidment)',
       'Natsch, Mr. Charles H', 'Healy, Miss. Hanora "Nora"',
       'Andrews, Miss. Kornelia Theodosia',
       'Lindblom, Miss. Augusta Charlotta', 'Parkes, Mr. Francis "Frank"',
       'Rice, Master. Eric', 'Abbott, Mrs. Stanton (Rosa Hunt)',
       'Duane, Mr. Frank', 'Olsson, Mr. Nils Johan Goransson',
       'de Pelsmaeker, Mr. Alfons', 'Dorking, Mr. Edward Arthur',
       'Smith, Mr. Richard William', 'Stankovic, Mr. Ivan',
       'de Mulder, Mr. Theodore', 'Naidenoff, Mr. Penko',
       'Hosono, Mr. Masabumi', 'Connolly, Miss. Kate',
       'Barber, Miss. Ellen "Nellie"',
       'Bishop, Mrs. Dickinson H (Helen Walton)',
       'Levy, Mr. Rene Jacques', 'Haas, Miss. Aloisia',
       'Mineff, Mr. Ivan', 'Lewy, Mr. Ervin G', 'Hanna, Mr. Mansour',
       'Allison, Miss. Helen Loraine', 'Saalfeld, Mr. Adolphe',
       'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
       'Kelly, Miss. Anna Katherine "Annie Kate"', 'McCoy, Mr. Bernard',
       'Johnson, Mr. William Cahoone Jr', 'Keane, Miss. Nora A',
       'Williams, Mr. Howard Hugh "Harry"',
       'Allison, Master. Hudson Trevor', 'Fleming, Miss. Margaret',
       'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
       'Abelson, Mr. Samuel', 'Francatelli, Miss. Laura Mabel',
       'Hays, Miss. Margaret Bechstein', 'Ryerson, Miss. Emily Borie',
       'Lahtinen, Mrs. William (Anna Sylfven)', 'Hendekovic, Mr. Ignjac',
       'Hart, Mr. Benjamin', 'Nilsson, Miss. Helmina Josefina',
       'Kantor, Mrs. Sinai (Miriam Sternin)', 'Moraweck, Dr. Ernest',
       'Wick, Miss. Mary Natalie',
       'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
       'Dennis, Mr. Samuel', 'Danoff, Mr. Yoto',
       'Slayter, Miss. Hilda Mary',
       'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
       'Sage, Mr. George John Jr', 'Young, Miss. Marie Grice',
       'Nysveen, Mr. Johan Hansen', 'Ball, Mrs. (Ada E Hall)',
       'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
       'Hippach, Miss. Jean Gertrude', 'McCoy, Miss. Agnes',
       'Partner, Mr. Austen', 'Graham, Mr. George Edward',
       'Vander Planke, Mr. Leo Edmondus',
       'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
       'Denkoff, Mr. Mitto', 'Pears, Mr. Thomas Clinton',
       'Burns, Miss. Elizabeth Margaret', 'Dahl, Mr. Karl Edwart',
       'Blackwell, Mr. Stephen Weart', 'Navratil, Master. Edmond Roger',
       'Fortune, Miss. Alice Elizabeth', 'Collander, Mr. Erik Gustaf',
       'Sedgwick, Mr. Charles Frederick Waddington',
       'Fox, Mr. Stanley Hubert', 'Brown, Miss. Amelia "Mildred"',
       'Smith, Miss. Marion Elsie',
       'Davison, Mrs. Thomas Henry (Mary E Finck)',
       'Coutts, Master. William Loch "William"', 'Dimic, Mr. Jovan',
       'Odahl, Mr. Nils Martin', 'Williams-Lambert, Mr. Fletcher Fellows',
       'Elias, Mr. Tannous', 'Arnold-Franchi, Mr. Josef',
       'Yousif, Mr. Wazli', 'Vanden Steen, Mr. Leo Peter',
       'Bowerman, Miss. Elsie Edith', 'Funk, Miss. Annie Clemmer',
       'McGovern, Miss. Mary', 'Mockler, Miss. Helen Mary "Ellie"',
       'Skoog, Mr. Wilhelm', 'del Carlo, Mr. Sebastiano',
       'Barbara, Mrs. (Catherine David)', 'Asim, Mr. Adola',
       "O'Brien, Mr. Thomas", 'Adahl, Mr. Mauritz Nils Martin',
       'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
       'Moussa, Mrs. (Mantoura Boulos)', 'Jermyn, Miss. Annie',
       'Aubart, Mme. Leontine Pauline', 'Harder, Mr. George Achilles',
       'Wiklund, Mr. Jakob Alfred', 'Beavan, Mr. William Thomas',
       'Ringhini, Mr. Sante', 'Palsson, Miss. Stina Viola',
       'Meyer, Mrs. Edgar Joseph (Leila Saks)',
       'Landergren, Miss. Aurora Adelia', 'Widener, Mr. Harry Elkins',
       'Betros, Mr. Tannous', 'Gustafsson, Mr. Karl Gideon',
       'Bidois, Miss. Rosalie', 'Nakid, Miss. Maria ("Mary")',
       'Tikkanen, Mr. Juho',
       'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
       'Plotcharsky, Mr. Vasil', 'Davies, Mr. Charles Henry',
       'Goodwin, Master. Sidney Leonard', 'Buss, Miss. Kate',
       'Sadlier, Mr. Matthew', 'Lehmann, Miss. Bertha',
       'Carter, Mr. William Ernest', 'Jansson, Mr. Carl Olof',
       'Gustafsson, Mr. Johan Birger', 'Newell, Miss. Marjorie',
       'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
       'Johansson, Mr. Erik', 'Olsson, Miss. Elina',
       'McKane, Mr. Peter David', 'Pain, Dr. Alfred',
       'Trout, Mrs. William H (Jessie L)', 'Niskanen, Mr. Juha',
       'Adams, Mr. John', 'Jussila, Miss. Mari Aina',
       'Hakkarainen, Mr. Pekka Pietari', 'Oreskovic, Miss. Marija',
       'Gale, Mr. Shadrach', 'Widegren, Mr. Carl/Charles Peter',
       'Richards, Master. William Rowe',
       'Birkeland, Mr. Hans Martin Monsen', 'Lefebre, Miss. Ida',
       'Sdycoff, Mr. Todor', 'Hart, Mr. Henry', 'Minahan, Miss. Daisy E',
       'Cunningham, Mr. Alfred Fleming', 'Sundman, Mr. Johan Julian',
       'Meek, Mrs. Thomas (Annie Louise Rowley)',
       'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
       'Silven, Miss. Lyyli Karoliina', 'Matthews, Mr. William John',
       'Van Impe, Miss. Catharina', 'Gheorgheff, Mr. Stanio',
       'Charters, Mr. David', 'Zimmerman, Mr. Leo',
       'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
       'Rosblom, Mr. Viktor Richard', 'Wiseman, Mr. Phillippe',
       'Clarke, Mrs. Charles V (Ada Maria Winfield)',
       'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
       'Flynn, Mr. James', 'Pickard, Mr. Berk (Berk Trembisky)',
       'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
       'Thorneycroft, Mrs. Percival (Florence Kate White)',
       'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
       'Kallio, Mr. Nikolai Erland', 'Silvey, Mr. William Baird',
       'Carter, Miss. Lucile Polk',
       'Ford, Miss. Doolina Margaret "Daisy"',
       'Richards, Mrs. Sidney (Emily Hocking)', 'Fortune, Mr. Mark',
       'Kvillner, Mr. Johan Henrik Johannesson',
       'Hart, Mrs. Benjamin (Esther Ada Bloomfield)', 'Hampe, Mr. Leon',
       'Petterson, Mr. Johan Emil', 'Reynaldo, Ms. Encarnacion',
       'Johannesen-Bratthammer, Mr. Bernt', 'Dodge, Master. Washington',
       'Mellinger, Miss. Madeleine Violet', 'Seward, Mr. Frederic Kimber',
       'Baclini, Miss. Marie Catherine', 'Peuchen, Major. Arthur Godfrey',
       'West, Mr. Edwy Arthur', 'Hagland, Mr. Ingvald Olai Olsen',
       'Foreman, Mr. Benjamin Laventall', 'Goldenberg, Mr. Samuel L',
       'Peduzzi, Mr. Joseph', 'Jalsevac, Mr. Ivan',
       'Millet, Mr. Francis Davis', 'Kenyon, Mrs. Frederick R (Marion)',
       'Toomey, Miss. Ellen', "O'Connor, Mr. Maurice",
       'Anderson, Mr. Harry', 'Morley, Mr. William', 'Gee, Mr. Arthur H',
       'Milling, Mr. Jacob Christian', 'Maisner, Mr. Simon',
       'Goncalves, Mr. Manuel Estanslas', 'Campbell, Mr. William',
       'Smart, Mr. John Montgomery', 'Scanlan, Mr. James',
       'Baclini, Miss. Helene Barbara', 'Keefe, Mr. Arthur',
       'Cacic, Mr. Luka', 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
       'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
       'Strandberg, Miss. Ida Sofia', 'Clifford, Mr. George Quincy',
       'Renouf, Mr. Peter Henry', 'Braund, Mr. Lewis Richard',
       'Karlsson, Mr. Nils August', 'Hirvonen, Miss. Hildur E',
       'Goodwin, Master. Harold Victor',
       'Frost, Mr. Anthony Wood "Archie"', 'Rouse, Mr. Richard Henry',
       'Turkula, Mrs. (Hedwig)', 'Bishop, Mr. Dickinson H',
       'Lefebre, Miss. Jeannie',
       'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
       'Kent, Mr. Edward Austin', 'Somerton, Mr. Francis William',
       'Coutts, Master. Eden Leslie "Neville"',
       'Hagland, Mr. Konrad Mathias Reiersen', 'Windelov, Mr. Einar',
       'Molson, Mr. Harry Markland', 'Artagaveytia, Mr. Ramon',
       'Stanley, Mr. Edward Roland', 'Yousseff, Mr. Gerious',
       'Eustis, Miss. Elizabeth Mussey',
       'Shellard, Mr. Frederick William',
       'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
       'Svensson, Mr. Olof', 'Calic, Mr. Petar', 'Canavan, Miss. Mary',
       "O'Sullivan, Miss. Bridget Mary", 'Laitinen, Miss. Kristina Sofia',
       'Maioni, Miss. Roberta',
       'Penasco y Castellana, Mr. Victor de Satode',
       'Quick, Mrs. Frederick Charles (Jane Richards)',
       'Bradley, Mr. George ("George Arthur Brayton")',
       'Olsen, Mr. Henry Margido', 'Lang, Mr. Fang',
       'Daly, Mr. Eugene Patrick', 'Webber, Mr. James',
       'McGough, Mr. James Robert',
       'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
       'Coleff, Mr. Satio', 'Walker, Mr. William Anderson',
       'Lemore, Mrs. (Amelia Milley)', 'Ryan, Mr. Patrick',
       'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
       'Pavlovic, Mr. Stefo', 'Perreault, Miss. Anne', 'Vovk, Mr. Janko',
       'Lahoud, Mr. Sarkis',
       'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
       'Kassem, Mr. Fared', 'Farrell, Mr. James', 'Ridsdale, Miss. Lucy',
       'Farthing, Mr. John', 'Salonen, Mr. Johan Werner',
       'Hocking, Mr. Richard George', 'Quick, Miss. Phyllis May',
       'Toufik, Mr. Nakli', 'Elias, Mr. Joseph Jr',
       'Peter, Mrs. Catherine (Catherine Rizk)', 'Cacic, Miss. Marija',
       'Hart, Miss. Eva Miriam', 'Butt, Major. Archibald Willingham',
       'LeRoy, Miss. Bertha', 'Risien, Mr. Samuel Beard',
       'Frolicher, Miss. Hedwig Margaritha', 'Crosby, Miss. Harriet R',
       'Andersson, Miss. Ingeborg Constanzia',
       'Andersson, Miss. Sigrid Elisabeth', 'Beane, Mr. Edward',
       'Douglas, Mr. Walter Donald', 'Nicholson, Mr. Arthur Ernest',
       'Beane, Mrs. Edward (Ethel Clarke)', 'Padro y Manent, Mr. Julian',
       'Goldsmith, Mr. Frank John', 'Davies, Master. John Morgan Jr',
       'Thayer, Mr. John Borland Jr', 'Sharp, Mr. Percival James R',
       "O'Brien, Mr. Timothy", 'Leeni, Mr. Fahim ("Philip Zenni")',
       'Ohman, Miss. Velin', 'Wright, Mr. George',
       'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
       'Robbins, Mr. Victor', 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
       'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
       'Morrow, Mr. Thomas Rowan', 'Sivic, Mr. Husein',
       'Norman, Mr. Robert Douglas', 'Simmons, Mr. John',
       'Meanwell, Miss. (Marion Ogden)', 'Davies, Mr. Alfred J',
       'Stoytcheff, Mr. Ilia',

In [21]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [23]:
df['Survived'].unique()

array([0, 1])

## Oridnal Variable

In [24]:
df['Pclass']

PassengerId
1      3
2      1
3      3
4      1
5      3
6      3
7      1
8      3
9      3
10     2
11     3
12     1
13     3
14     3
15     3
16     2
17     3
18     2
19     3
20     3
21     2
22     2
23     3
24     1
25     3
26     3
27     3
28     1
29     3
30     3
      ..
862    2
863    1
864    3
865    2
866    2
867    2
868    1
869    3
870    3
871    3
872    1
873    1
874    3
875    2
876    3
877    3
878    3
879    3
880    1
881    2
882    3
883    3
884    2
885    3
886    3
887    2
888    1
889    3
890    1
891    3
Name: Pclass, Length: 891, dtype: int64

In [25]:
df['Pclass'].unique()

array([3, 1, 2])